name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    env:
      FORCE_COLOR: "1"

    name: Tests with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}-dev
          architecture: x64

      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install poetry nox nox-poetry

      - name: Run nox
        run: |
          nox --python=${{ matrix.python-version }}

      - name: Publish coverage metrics
        run: |
          nox -rs coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
